[project]
name = "rojo-print"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "folium>=0.19.6",
    "geopy>=2.4.1",
    "ruff>=0.11.12",
    "streamlit>=1.45.1",
    "streamlit-folium>=0.25.0",
]
